sudo: false
language: go
go: 1.4
script: set -o pipefail && ( seq 1 3 && mv output.txt{,.1} && seq 4 6 && sleep 1 && mv output.txt{,.2} && seq 7 9 && sleep 1 && mv output.txt{,.3} ) | log2file output.txt
before_deploy:
    - GOOS=linux GOARCH=amd64 go build -o log2file_linux_amd64 log2file.go
deploy:
  provider: releases
  api_key:
    secure: smZSPXYeFYKqsYEBlsGnj35AL+8TyG9u7O8gJqlSb+IFylbHZyxllcO8hVCBc3qqSagxpYZPFf+CTrWr63VYEUdar9dBrJs+HQiChZOFPLM9iTJJzZ6FHMpM3P/2rRq9iVSqYZfLpebN1afUgM+aNbQG6hTxxpXYzKISXItWtbk=
  file: log2file_linux_amd64
  on:
    repo: genome/log2file
    all_branches: true
    tags: true
    go: go1.4
